Update ginkgo v2
BishopFox/guardian-ci pull request #67
Opened 2022-05-30 14:56 UTC by ZabdiAG

#### Card

#### Details

2022-05-31 15:55 UTC, alistair-mclean approved these changes

2022-06-01 15:22 UTC, ricardoBISHOP requested changes
this command is used for many repos,
create a new one for v2 and leave this one for the moment while we finish updating the rest of the repos to v2

2022-06-01 16:24 UTC, ricardoBISHOP approved these changes

2022-06-01 16:53 UTC, mattkeeler approved these changes

2022-06-01 16:56 UTC, merged